class DuckEmojis {
  static const String basePath = 'assets/images/DuckEmoji/';

  static const String work = '${basePath}86_WORK_OUT.json';
  static const String personal = '${basePath}101_HOME_OUT.json';
  static const String sport = '${basePath}99_SPORT_OUT.json';
  static const String study = '${basePath}74_BOTAN_OUT.json';
  static const String shopping = '${basePath}100_SHOP_OUT.json';
  static const String health = '${basePath}81_VIRUS_OUT.json';
  static const String finance = '${basePath}71_MONEY_OUT.json';
  static const String travel = '${basePath}103_PLANE_OUT.json';
  static const String academic = '${basePath}96_EDU_OUT.json';
  static const String fire = '${basePath}65_FIRE_OUT.json';
  static const String hypn = '${basePath}29_HYPN_OUT.json';
  static const String other = '${basePath}28_BRRR_OUT.json'; 

  static const List<String> all = [
    '${basePath}01_KISS_OUT.json',
    '${basePath}02_HAHA_OUT.json',
    '${basePath}03_SHOKE_OUT.json',
    '${basePath}04_MIMIMI_OUT.json',
    '${basePath}05_HEARTS_OUT.json',
    '${basePath}06_REDANGRY_OUT.json',
    '${basePath}07_SAD_OUT.json',
    '${basePath}08_CRYING_OUT.json',
    '${basePath}09_EYES_OUT.json',
    '${basePath}10_STEAM_OUT.json',
    '${basePath}11_NEUTRAL_OUT.json',
    '${basePath}12_MUHAHA_OUT.json',
    '${basePath}13_WINK_OUT.json',
    '${basePath}14_WINKISS_OUT.json',
    '${basePath}15_ANGRY_OUT.json',
    '${basePath}16_HMM_OUT.json',
    '${basePath}17_EYEBR_OUT.json',
    '${basePath}18_ZZZ_OUT.json',
    '${basePath}19_TEETH_OUT.json',
    '${basePath}21_LOL_OUT.json',
    '${basePath}22_SADFISH_OUT.json',
    '${basePath}23_THERMO_OUT.json',
    '${basePath}24_MEH_OUT.json',
    '${basePath}25_TONGUE_OUT.json',
    '${basePath}26_CRAZY_OUT.json',
    '${basePath}27_HIH_DROP_OUT.json',
    '${basePath}28_BRRR_OUT.json',
    '${basePath}29_HYPN_OUT.json',
    '${basePath}30_EVIL_OUT.json',
    '${basePath}31_EVIL_HEHE_OUT.json',
    '${basePath}32_PARTY_OUT.json',
    '${basePath}33_SCREAM_OUT.json',
    '${basePath}34_DEAL_OUT.json',
    '${basePath}35_MUHAHA_OUT.json',
    '${basePath}36_MUAHTEETH_OUT.json',
    '${basePath}37_HAPPYEYES_OUT.json',
    '${basePath}38_SMILECRY_OUT.json',
    '${basePath}39_SCARY_OUT.json',
    '${basePath}40_YUM_OUT.json',
    '${basePath}41_STARS_OUT.json',
    '${basePath}42_CHIKS_OUT.json',
    '${basePath}44_OUFF_OUT.json',
    '${basePath}45_WAAA_OUT.json',
    '${basePath}46_WEEE_OUT.json',
    '${basePath}47_HEARTS_OUT.json',
    '${basePath}48_YAZYK_OUT.json',
    '${basePath}49_BARF_OUT.json',
    '${basePath}50_F_OUT.json',
    '${basePath}51_UPSIDE_OUT.json',
    '${basePath}52_CRY_OUT.json',
    '${basePath}53_LIKE_OUT.json',
    '${basePath}54_OK_OUT.json',
    '${basePath}55_ANGEL_OUT.json',
    '${basePath}56_SMIRG_OUT.json',
    '${basePath}57_HOT_OUT.json',
    '${basePath}58_JOKER_OUT.json',
    '${basePath}59_POO_OUT.json',
    '${basePath}60_RELIEF_OUT.json',
    '${basePath}61_OU_HAND_OUT.json',
    '${basePath}62_OOH_OUT.json',
    '${basePath}63_MIMIHAND_OUT.json',
    '${basePath}64_JAR_OUT.json',
    '${basePath}65_FIRE_OUT.json',
    '${basePath}66_DEAD_OUT.json',
    '${basePath}67_SLEEPY_OUT.json',
    '${basePath}68_DISLIKE_OUT.json',
    '${basePath}69_APPL_OUT.json',
    '${basePath}70_HEY_OUT.json',
    '${basePath}71_MONEY_OUT.json',
    '${basePath}72_QUACK_OUT.json',
    '${basePath}73_MONOCLE_OUT.json',
    '${basePath}74_BOTAN_OUT.json',
    '${basePath}75_SKULL_OUT.json',
    '${basePath}76_ILL_OUT.json',
    '${basePath}77_SHH_OUT.json',
    '${basePath}78_DRUNK_OUT.json',
    '${basePath}79_ZIP_OUT.json',
    '${basePath}80_MINDBLO_OUT.json',
    '${basePath}81_VIRUS_OUT.json',
    '${basePath}82_SAD_OUT.json',
    '${basePath}83_COLD_OUT.json',
    '${basePath}85_FINGERHEART_OUT.json',
    '${basePath}86_WORK_OUT.json',
    '${basePath}87_BATH_OUT.json',
    '${basePath}88_OFF_OUT.json',
    '${basePath}89_MELT_OUT.json',
    '${basePath}90_BUEH_OUT.json',
    '${basePath}91_-_-_OUT.json',
    '${basePath}92_SPIT_OUT.json',
    '${basePath}93_PAR_OUT.json',
    '${basePath}94_BEACH_OUT.json',
    '${basePath}95_EAT_OUT.json',
    '${basePath}96_EDU_OUT.json',
    '${basePath}97_TOILET_OUT.json',
    '${basePath}98_FU_OUT.json',
    '${basePath}99_SPORT_OUT.json',
    '${basePath}100_SHOP_OUT.json',
    '${basePath}101_HOME_OUT.json',
    '${basePath}102_JAIL_OUT.json',
    '${basePath}103_PLANE_OUT.json',
    '${basePath}104_PHONE_OUT.json',
    '${basePath}105_PRAY_OUT.json',
    '${basePath}106_DRIVE_OUT.json',
    '${basePath}107_BICE_OUT.json',
  ];
}
